### ISSUE TITLE
multi_to_single_fast5 fails with no error

### ISSUE THREAD

**Issue by pabloacera** [nanoporetech/ont_fast5_api#13]
Hi,

I am using multi_to_single_fast5 to convert this bulk fast5 file (https://s3.amazonaws.com/nanopore-human-wgs/rna/bulkFiles/PLSP57501_20171025_FAH20330_MN18458_sequencing_run_Notts_Run1_20171025_DirectRNA_49527.fast5) into single files.

The command im using is:
`multi_to_single_fast5 -i PLSP57501_20171025_FAH20330_MN18458_sequencing_run_Notts_Run1_20171025_DirectRNA_49527_multi/ -s single/`
I get this message:
`/home/pablo/.pyenv/versions/3.5.0/envs/bulkis/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
| 1 of 1|#######################################################################################################################################################|100% Time: 0:00:00`

and in the output file (single/filename_mapping.txt) is just written:
multi_read_file single_read_file

I don't find this error in any of the closed tickets, any idea of what could be happening?
Thank you very much in advance for your time and help!!

**Comment by fbrennen** [comment]
Hi @pabloacera -- what else do you see in your output folder? Are there subfolders in there with fast5 files in them, or is it only the `filename_mapping.txt` file?

**Comment by pabloacera** [comment]
Hi, is just the `filename_mapping.txt`file.

**Comment by fbrennen** [comment]
Hah, sorry, I should have read your issue more carefully. `multi_to_single_fast5` works on multi-read fast5 files, but not bulk files -- those are special diagnostic outputs for advanced users, and have a lot of extra things in them. You might want to check out the [fast5_research](https://github.com/nanoporetech/fast5_research) project, which has some tools in it to support extracting reads from bulk files.

https://nanoporetech.github.io/fast5_research/examples.html#bulk-files

**Comment by fbrennen** [comment]
Hah, sorry, I should have read your issue more carefully. `multi_to_single_fast5` works on multi-read fast5 files, but not bulk files -- those are special diagnostic outputs for advanced users, and have a lot of extra things in them. You might want to check out the [fast5_research](https://github.com/nanoporetech/fast5_research) project, which has some tools in it to support extracting reads from bulk files.

https://nanoporetech.github.io/fast5_research/examples.html#bulk-files

**Comment by pabloacera** [comment]
ouh I see, thanks a lot for your time and help!!
