### ISSUE TITLE
multi_to_single_fast5 no output

### ISSUE THREAD

**Issue by Shians** [nanoporetech/ont_fast5_api#14]
Taking the single reads from [here](https://github.com/nanoporetech/ont_fast5_api/tree/master/test/data/single_reads) and putting into a folder called `single`, I can run
```
single_to_multi_fast5single_fast5 -i single -s multi
```
fine and it produces a `batch_0.fast5  filename_mapping.txt`. But going the other way around
```
multi_to_single_fast5single_fast5 -i multi -s split
```
produces only `filename_mapping.txt` with no results.

I am on Ubuntu 18.04, no errors are shown, the program seems to complete successfully.

**Comment by fbrennen** [comment]
Hi @Shians -- what is the full output in your `split` folder? Did you get a subfolder labelled `0` ? That's what I get when I run the steps you've outlined:

```bash
root@225a679a4e4f:/# single_to_multi_fast5 -i ont_fast5_api/test/data/single_reads/ -s multi
| 1 of 1|#######################################################################################################|100% Time: 0:00:00
root@225a679a4e4f:/# ls multi
batch_0.fast5  filename_mapping.txt
root@225a679a4e4f:/# multi_to_single_fast5 -i multi/ -s split
| 1 of 1|#######################################################################################################|100% Time: 0:00:00
root@225a679a4e4f:/# ls split
0  filename_mapping.txt
root@225a679a4e4f:/# ls split/0
568b93db.fast5  5c5ef835.fast5  69e9e884.fast5  9171d66b.fast5
```

**Comment by Shians** [comment]
Ahh, my brain somehow ignored the 0. All working as intended then!

**Comment by fbrennen** [comment]
Good to hear! =)
