### ISSUE TITLE
fail to run fast5_subset

### ISSUE THREAD

**Issue by limin321** [nanoporetech/ont_fast5_api#17]
My data are nanopore data, and I convert all fast5 data to multi-read using single_to_multi_fast5. Then I want to extract all fast5 reads that belong to one bacterium strain together by running the following command:
fast5_subset --input ./multi_reads/ --save_path ./rub_server_fast5 --read_id_list ./rub/BC11_rub_headers.txt --recursive

However, it failed with the following informaiton:
Traceback (most recent call last):
  File "/afs/genomecenter.ucdavis.edu/home/limchen/.local/bin/fast5_subset", line 10, in <module>
    sys.exit(main())
  File "/home/limchen/.local/lib/python2.7/site-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 288, in main
    recursive=args.recursive, file_list_file=args.file_list)
  File "/home/limchen/.local/lib/python2.7/site-packages/ont_fast5_api/conversion_tools/multi_fast5_subset.py", line 33, in __init__
    assert path.isdir(input_folder)
AssertionError

Though it does produce some data and store in the output folder--rub_server_fast5, I still get the above information. Can anyone explain to me what is the problem with my fast5_subset, and how to solve it.

Your help are greatly appreciated. Thank you so much in advance.

**Comment by fbrennen** [comment]
Hi @limin321 -- the error above suggests that your input path `./multi_reads/` is not a directory. Can you check and make sure it exists, and has the correct name?

**Comment by fbrennen** [comment]
Hi @limin321 -- is your file conversion working now?

**Comment by limin321** [comment]
> Hi @limin321 -- is your file conversion working now?

Hi fbrennen,

Thank you for asking again.  
I double check multi_reads. It is a directory and has the files, here is the picture.

<img width="1223" alt="Screen Shot 2019-07-08 at 12 05 17 PM" src="https://user-images.githubusercontent.com/42760669/60835712-b23cfe80-a178-11e9-8d6a-c4fb5508c25d.png">

**Comment by fbrennen** [comment]
Great, thanks. What does the output folder look like? Did you get the reads you expected there, or are some missing?

**Comment by limin321** [comment]
attached is the information running failed again.
here is output folder, the size is not right, only 512.
[image: Screen Shot 2019-07-09 at 8.57.26 AM.png]

**Comment by fbrennen** [comment]
Hi @limin321 -- just continuing to check in to this. Can you send me a screenshot of the full command you used to run `fast5_subset`, including the folder you ran it in? (The screenshot you sent in your previous email reply didn't actually show up, by the way.) And can you confirm the version of ont-fast5-api you're using?
