### ISSUE TITLE
feature request : add tar as input format for single_to_multi_fast5

### ISSUE THREAD

**Issue by svennd** [nanoporetech/ont_fast5_api#2]
Would it be possible to add .tar as input format for single_to_multi_fast5 ? I believe allot of customers that store fast5's have already made tars of these to save the filesystem from a inode/rsync hangover.

**Comment by fbrennen** [comment]
Hi @svennd -- other than ease of use, is there a particular reason you don't want to just untar each file first before converting it?

**Comment by svennd** [comment]
Its mainly the ease of use; But wear & tear of writing the same data two times could be a good reason. 
tar -> single fast5's -> multi fast5.  If this tool can load 4k reads in memory from a tar, no write would be required to store the temporary single fast5's. Considering the current raw data size per run (~2TB) that's a big win for those poor disks ;-) 

Site specific for us, we store raw data on tape, so if we could directly get a valid format from our tape that would be a good thing.

**Comment by fbrennen** [comment]
Sure, ok, we can think about that. I believe it will be a non-trivial addition so it's likely to take a while to make it up the priority list.
