### ISSUE TITLE
multi_to_single_fast5 outputted single fast5 files without content for Albacore base-calling

### ISSUE THREAD

**Issue by BisonKok** [nanoporetech/ont_fast5_api#20]
I was trying to output single fast5 files from multiple fast5 files (multiple fast5 files were produced since MinKNOW ver. 3.1.19). The reason is because I want to use **Albcore** for base-calling. The command is as below:
`multi_to_single_fast5 --input_path ./fast5/ --save_path ./out_folder --recursive -t 20`

The single fast5 files could be outputted. However, when using Albacore for base-calling, there is no base-called fast5 and fastq outputted (All fast5 files were found to be "empty"). The command for Albacore execution is as below:
`read_fast5_basecaller.py -i out_folder/ -t 8 -s ./basecalled_output -r -k SQK-RNA001 -f FLO-MIN106 -o fast5,fastq --disable_filtering`
 
By the way, I do not have issue base-calling with Guppy as Guppy outputted both fast5 and fastq files with content. 

Is there something wrong with the commands? Thanks in advance.

**Comment by fbrennen** [comment]
Hi @BisonKok -- could you provide a bit more information about the error message you see in albacore (check inside the logs), the version of albacore you're using, and maybe one or two single-read fast5 files that you have issues with? Thanks!
