### ISSUE TITLE
ValueError: mpi4py.MPI.Status size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by fbrennen** [nanoporetech/ont_fast5_api#21]
I'm trying to use either the fast5_subset or single_to_multi_fast5 and I keep getting this error anytime I try and run one of the console scripts:

ValueError: mpi4py.MPI.Status size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

these are the versions of my dependancies...do i need to be running a specific version of openmpi?

ont-fast5-api (1.4.7)
progressbar33 (2.4)
six (1.12.0) 
numpy (1.17.0)
h5py (2.9.0)

_Originally posted by @behrimg in https://github.com/nanoporetech/ont_fast5_api/issues/19#issuecomment-516057738_

**Comment by fbrennen** [comment]
Hi @behrimg -- a quick google suggests that might have occurred if you've built hdf5 yourself or otherwise installed the version that allows for parallel process communication. Did you do that? Could you try creating a new virtual environment, installing ont-fast5-api in there, and then testing again? You should not need to do anything special with any packages, including openmpi.

**Comment by behrimg** [comment]
No, it looks like the problem was my python version. It's working fine in python 2.7 from anaconda2. But not when using python 3.7 in anaconda3. There might be something off about the packages installed between the two versions on my end but I'm not getting the error above anymore.

**Comment by fbrennen** [comment]
Great! A bit odd about python3 giving you trouble, but I'm glad you got it working.
