### ISSUE TITLE
'<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by malkadi89** [nanoporetech/ont_fast5_api#23]
Suddenly it gives me a message error 

ont_fast5_api.conversion_tools.single_to_multi_fast5:'<' not supported between instances of 'str' and 'float'        |  0% ETA:  --:--:--
        Failed to add single read file: './FAK47977_78c30614cc65b2b97c46e55b3057dc404e30b4db_0.fast5' to './batch_0.fast5'

although it worked before on the same file. I tried other files and have the same result.

Regards,

**Comment by fbrennen** [comment]
Hi @malkadi89 -- could we have a look at your input fast5 file (that "78c306" one)?

**Comment by malkadi89** [comment]
this is a link to the file: 
https://1drv.ms/u/s!Asm8Mm-2WNRGl1SfUwKqOZkONUV_?e=lWDgz7
I tried a different machine and I got this message too
Failed to add single read file: './9b777316-6ca3-437f-8b41-cd97b9dee809.fast5' to './test/batch_0.fast5'
ERROR:ont_fast5_api.conversion_tools.single_to_multi_fast5:local variable 'global_keys' referenced before assignment. 

I got the message with the test data too.

Regards,

**Comment by fbrennen** [comment]
That's a multi-read file you've sent, not a single-read one, so `single_to_multi` isn't going to work well there (as it's not actually necessary). Did you mean to run that script, or did you want to run `multi_to_single` instead?

**Comment by malkadi89** [comment]
I am very sorry. I didn't pay attention to the file type. I posted here after spending hours trying to solve the problem because I used the tool before but this time I made a mistake. Sorry again for the inconvenience. 

Regards,

**Comment by fbrennen** [comment]
No problem at all -- glad we got this fixed for you. =)

**Comment by wdecoster** [comment]
Just got tripped by this as well (cleaning up older data, didn't know these reads were already multiread). Do you think a more explicit error would be possible?

**Comment by fbrennen** [comment]
Yes, absolutely -- in version 2.1. of the file schema we're going to add an explicit file type as metadata, and that will allow us to reliably detect single- and multi-read files, and return a more sensible error message.

**Comment by wdecoster** [comment]
Perfect, thanks!
