### ISSUE TITLE
different filesize after "de-" compression

### ISSUE THREAD

**Issue by svennd** [nanoporetech/ont_fast5_api#30]
To take advantage of the new vbz compression, we compressed some older runs first; To check if these contained all the data, I tried to uncompress again using gzip. The results however show different file sizes then the original; How can this be explained, is there some data lost ? 

For example :
original filesize : 625977982
compress_fast5 -i original -c gzip  : 625856958
compress_fast5 -i original -c vbz : 445306389
compress_fast5 -i vbz -c gzip : 569231217

I expected a slight difference due to access time, but this seems to big for this ? Going from gzip (by default ?) to lz4 to gzip results in a smaller file.

I tried to use h5diff and it does give differences but when I set it to report I get a bunch of "0 differences found".

**Comment by fbrennen** [comment]
Hi @svennd -- that's quite interesting! The initial obvious candidate is compression level: when switching compression from vbz to gzip we use the default gzip compression level that h5py uses. That default is compression level 4, which compresses data a little bit better than lower levels but takes slightly longer to run. The default gzip compression level that MinKNOW uses is 1 (because they want file output to be as fast as possible), so it would be understandable to see a small decrease to the original file size. Your change of ~10% seems far in excess of a "small decrease" though. You're absolutely sure about those sizes?

You can see the compression details by running `h5dump -pH <file>` -- you should see something like this for the `Signal` sections where vbz gets used:

```
[...]
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 16224 ) / ( 16224 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4056 )
               SIZE 18074 (1.795:1 COMPRESSION)
            }
            FILTERS {
               PREPROCESSING SHUFFLE
               COMPRESSION DEFLATE { LEVEL 4 }
            }
[...]
```
(for gzip -- note the `LEVEL 4` in there as I've used `compress_fast5` to generate this)

or
```
[...]
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 16224 ) / ( 16224 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4056 )
               SIZE 13924 (2.330:1 COMPRESSION)
            }
            FILTERS {
               USER_DEFINED_FILTER {
                  FILTER_ID 32020
                  COMMENT vbz
                  PARAMS { 1 2 1 1 }
               }
            }
[...]
```
(for vbz)

What do you see when you look at the same Signal sections using that approach?

There is a known issue reported [here](https://github.com/nanoporetech/vbz_compression/issues/4) that can cause files to increase in size when compressing them using vbz, but that shouldn't produce a decrease in file size like you're seeing.

**Comment by svennd** [comment]
Thanks for the help; I redid with a single fast5 ;

Original file : 625977982 
```
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 152451 ) / ( H5S_UNLIMITED ) }
            STORAGE_LAYOUT {
               CHUNKED ( 201536 )
               SIZE 158988 (1.918:1 COMPRESSION)
            }
            FILTERS {
               COMPRESSION DEFLATE { LEVEL 1 }
            }
```
compress -i ori -c gzip : 625856958
```
         DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 152451 ) / ( H5S_UNLIMITED ) }
            STORAGE_LAYOUT {
               CHUNKED ( 201536 )
               SIZE 158988 (1.918:1 COMPRESSION)
            }
            FILTERS {
               COMPRESSION DEFLATE { LEVEL 1 }
            }
```

compress -i ori -c vbz : 445306389
```
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 152451 ) / ( 152451 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4765 )
               SIZE 108019 (2.823:1 COMPRESSION)
            }
            FILTERS {
               USER_DEFINED_FILTER {
                  FILTER_ID 32020
                  COMMENT vbz
```

compress -i vbz-c gzip : 569231217
 ```
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 152451 ) / ( 152451 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4765 )
               SIZE 143685 (2.122:1 COMPRESSION)
            }
            FILTERS {
               PREPROCESSING SHUFFLE
               COMPRESSION DEFLATE { LEVEL 4 }
```

I copied the last read only. (these where originally non multi fast5 files)

I guess that solves some of my initial questions : 
1) When the input is gzip compressed, no extra compression is applied, the file difference is small and might be explained by the database format ?
2) When input is gzip -> vbz -> gzip, in the last step, the vbz is changed to gzip level = 4 explaining the difference between the original gzip and the new gzip.

I understand for processing speed gzip level = 1 or gzip level = 4 are fair, but for long time storage, gzip level = 9 might be useful, can we adapt this ? or can this be a feature request ? (or can we hack this)

In the level 4 file the "filters" is also added : "PREPROCESSING SHUFFLE" does this impact the data ?

The compression ratio over the datasets are really good actually, we get between 27 and 41% reduction by using vbz; with an avg of 33%.  (all human) I just want to be sure we can remove the original fast5's w/o losing essential data :) So I don't think we face a similar issue;

**Comment by fbrennen** [comment]
Ah ha -- great work! Adding that shuffle preprocessing step [rearranges data](http://docs.h5py.org/en/stable/high/dataset.html#shuffle-filter) to make it easier to compress -- I was not aware that MinKNOW wasn't using it, and that will account for the unexpectedly large gains you're seeing. Here's the dataset I showed you above compressed without shuffling:

```
[...]
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 16224 ) / ( 16224 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4056 )
               SIZE 21202 (1.530:1 COMPRESSION)
            }
            FILTERS {
               COMPRESSION DEFLATE { LEVEL 4 }
            }
[...]
```
That's really good to know. =) I'll mention this to the MinKNOW team.

The reason we don't meddle with the compression level of gzip is that, shuffle filter aside, the difference between compression level 1 and level 9 is quite small, but the increase in processing time to compress the data is significant. For example, looking again at the above read:

```
DATASET "Signal" {
            DATATYPE  H5T_STD_I16LE
            DATASPACE  SIMPLE { ( 16224 ) / ( 16224 ) }
            STORAGE_LAYOUT {
               CHUNKED ( 4056 )
               SIZE 17760 (1.827:1 COMPRESSION)
            }
            FILTERS {
               PREPROCESSING SHUFFLE
               COMPRESSION DEFLATE { LEVEL 9 }
            }
```
It's only gone from 1.795:1 to 1.827:1 (about 1%), but offscreen the time to compress the file has gone up by about 15%.

Vbz is also a *lot* better at this (as you've noticed), so if you're after the best long-term compression I would recommend using that instead. If you've got a desperate need for gzip level 9 it's easy to hack in (by editing the compression settings module to add `compression_opts=9`), or we could look into adding it.
