### ISSUE TITLE
Type incompatibility in Fast5Info constructor

### ISSUE THREAD

**Issue by lfearnley** [nanoporetech/ont_fast5_api#32]
Hi all,

I've run across an issue where I'm seeing some problems around casting of version information in fast5s when constructing a Fast5Info object from fast5_info.py. I have h5py==2.10.0 and ont-fast5-api==3.0.1.

The problem seems to be in checking version information:

`self.version = _clean(handle.attrs['file_version'])`
`if self.version < 0.6:` # Exception here.

The error is:

`  File "/anaconda/lib/python3.6/site-packages/ont_fast5_api/fast5_info.py", line 63, in __init__
    if self.version < 0.6:
TypeError: '<' not supported between instances of 'str' and 'float'
`
Looking at debugging this a little, it appears that handle.attrs['file_version'] is being stored as a numpy.bytes_ object (specifically b'1.0' on this file), and the _clean method is converting this to a string.

**Comment by fbrennen** [comment]
Hi @lfearnley -- thanks very much for that! We'll get this fixed.

**Comment by lfearnley** [comment]
No worries, thanks for the software! :)

**Comment by fbrennen** [comment]
Ah, it's also worth noting based on [this previous issue](https://github.com/nanoporetech/ont_fast5_api/issues/23) that you may be using a file type with the wrong script -- e.g. a multi-read file with `single_to_multi_fast5`. Doesn't mean we shouldn't fix the underlying issue of course. =)

**Comment by fbrennen** [comment]
Fixed in version 3.0.2.
