### ISSUE TITLE
fast5_subset on vbz compressed fast5 files

### ISSUE THREAD

**Issue by Ganthark** [nanoporetech/ont_fast5_api#33]
Hi,

I was not able to run the fast5_subset on vbz compressed files. 
Here is the command I ran (on multiple samples a cluster):
`fast5_subset -f "reads" -i $fast5 -s $dir -l "${dir}/ids.txt"`
And the output for one of the samples:
`
Traceback (most recent call last):
  File "/home/cmatteoli/anaconda3/envs/Nanopore/bin/fast5_subset", line 8, in <module>
    sys.exit(main())
  File "/home/cmatteoli/anaconda3/envs/Nanopore/lib/python3.6/site-packages/ont_fast5_api/conversion_tools/fast5_subset.py", line 313, in main
    recursive=args.recursive, file_list_file=args.file_list, follow_symlinks=not args.ignore_symlinks)
  File "/home/cmatteoli/anaconda3/envs/Nanopore/lib/python3.6/site-packages/ont_fast5_api/conversion_tools/fast5_subset.py", line 52, in __init__
    "No input fast5 files found in {}. Recursion is set to {}".format(str(input_folder), recursive))
ValueError: No input fast5 files found in ../../../raw/Nanopore/Bd21/191012_Bd21-3/fast5/. Recursion is set to False
`
A little command to be sure the files are there:
`
$ ls ../../../raw/Nanopore/Bd21/191012_Bd21-3/fast5/ |  head -n 3
FAL51305_884535b6c19bcad13a639b636b466d83fb00966a_0.fast5.vbz
FAL51305_884535b6c19bcad13a639b636b466d83fb00966a_100.fast5.vbz
FAL51305_884535b6c19bcad13a639b636b466d83fb00966a_101.fast5.vbz
`

Maybe the extension I used is the problem? I ran other analysis on these files without any issue (mapping, nanopolish...) and I never had issues to subset fast5 before using the vbz compression.

Thank you for this great tool, I hope you can help!

**Comment by fbrennen** [comment]
Hi @Ganthark -- thanks for letting us know. We'll have a look.

**Comment by fbrennen** [comment]
Just to confirm, are you sure you're running `fast5_subset` from the same directory you're running that `ls` command from? We aren't displaying the absolute path of the input folder in that error message, which isn't very helpful (we'll fix that), so I can't tell just by looking what directory `fast5_subset` was run from.

**Comment by fbrennen** [comment]
Ah, sorry, I see the issue -- your files have the wrong extension! They need to end with `.fast5`, not `.vbz`.

**Comment by Ganthark** [comment]
I thought that might be the issue but I wanted to be sure before renaming everything.
Thank you for the quick response!
