### ISSUE TITLE
Decompress/repack from VBZ to GZIP or something option compatible with squiggle tools

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_fast5_api#34]
I have seen on the VBZ compression repository containing the not hdf5 plugin for working with VBZ compression but is there any plan to make a subtotal within ont_fast5_api? 

I am little apprehensive changing the -f parameter with h5repack and what it does exactly. It would also be good to have some system of naming output files matching the input for list of fast5 files.

**Comment by fbrennen** [comment]
Hi @callumparr -- are you looking for the `compress_fast5` script?

**Comment by callumparr** [comment]
I am looking for something like this but going from VBZ to GZIP so I can use on fast5 out files containing squiggles generated with master of pores pipeline that are then compatible with tailfindr and nanopolish polya

**Comment by fbrennen** [comment]
`compress_fast` goes both ways -- you can convert the raw dataset from gzip to vbz, and also from vbz to gzip. Is that good enough?

**Comment by callumparr** [comment]
Yeh sorry I think this is more to do my basic understanding of informatics.

**Comment by fbrennen** [comment]
Great, so you have everything you need then?

**Comment by callumparr** [comment]
Sorry forgot to close
