### ISSUE TITLE
sequencing_summary.txt for fast5_subset output

### ISSUE THREAD

**Issue by mmiladi** [nanoporetech/ont_fast5_api#35]
Hi,

The output fast5 files of `fast5_subset` program does not rproduce the sequencing_summary.txt. Is there a way to reproduce a summary file based on the original summary file? Or alternatively is there a way to generate summary file using the fast5 files without base calling again?

Also it would be great if this feature would be supported by the program.

Best,
-Milad

**Comment by fbrennen** [comment]
Hi @mmiladi -- `fast5_subset` produces a file called `filename_mapping.txt` that contains all the `read_id`s in the subset. You should be able to use that file to extract the relevant reads from your sequencing summary file very easily. Does that make sense?

**Comment by mmiladi** [comment]
Thanks for your reply @fbrennen . 
I would like to use the sequencing_summary.txt as input for the downstream tools (specifally nanopolish). So do you mean I intersect the Would you think I can intersect entry names `filename_mapping.txt` with the original `sequencing_summary.txt` to produce a new valid summary file?

**Comment by fbrennen** [comment]
Hi @mmiladi -- yes, you should be able to do exactly that.

**Comment by mmiladi** [comment]
Thanks for your assistance @fbrennen
