### ISSUE TITLE
Check if the Fast5 is multi-read or single-read

### ISSUE THREAD

**Issue by akk01** [nanoporetech/ont_fast5_api#39]
Is there any straightforward way to  check if the Fast5 is multi-read or single-read.

**Comment by fbrennen** [comment]
Hi @akk01 -- check out the `is_multi_fast5()` function in `fast5_interface` [here](https://github.com/nanoporetech/ont_fast5_api/blob/e707da5cb175dc85df1b4bc4de4b7bd7feb14c15/ont_fast5_api/fast5_interface.py#L36).
