### ISSUE TITLE
multi_to_single_fast5 command give syntax error

### ISSUE THREAD

**Issue by aman21392** [nanoporetech/ont_fast5_api#41]
command- multi_to_single_fast5 -i /home/aclab/nanopore/control_nanopore/fast5_pass/ -s /home/aclab/nanopore/control_nanopore --recursive

Traceback (most recent call last):
  File "/home/aclab/.local/bin/multi_to_single_fast5", line 7, in <module>
    from ont_fast5_api.conversion_tools.multi_to_single_fast5 import main
  File "/home/aclab/.local/lib/python2.7/site-packages/ont_fast5_api/__init__.py", line 10, in <module>
    from ont_fast5_api.compression_settings import register_plugin
  File "/home/aclab/.local/lib/python2.7/site-packages/ont_fast5_api/compression_settings.py", line 73
    raise IOError(VBZ_ERROR_MESSAGE.format(register_plugin())) from err
                                                                  ^
SyntaxError: invalid syntax

I don't understand why it give error. I have total 300 .fast5 which were guppy based call.
FAL21946_pass_bbdacd72_0.fast5
FAL21946_pass_bbdacd72_1.fast5
FAL21946_pass_bbdacd72_2.fast5
.
.
.
FAL21946_pass_bbdacd72_300.fast5

so i want it to convert into single.fast5 . 
Please give me suggestion and in advance thank you.

**Comment by fbrennen** [comment]
Hi @aman21392 -- what version of ont-fast5-api are you using? We don't support python 2 anymore (as it reached its official end of life last year), and that may have something to do with why you're having issues.

**Comment by aman21392** [comment]
pip install ont-fast5-api , I download directly from pip so it may be the latest version. I see some comment in your page and i tried command -
python3 multi_to_single_fast5 -i /home/aclab/nanopore/control_nanopore/fast5_pass/ -s /home/aclab/nanopore/control_nanopore --recursive 
But i got an error-
python3: can't open file 'multi_to_single_fast5': [Errno 2] No such file or directory
So please give some suggestion how to i find solution.
Thank you again

**Comment by fbrennen** [comment]
Great -- it looks like you'll need to re-install ont-fast5-api for python3 specifically. Try this:

`python3 -m pip install ont-fast5-api`

And then re-run that `python3 multi_to_single [...]` command.

We'll add a few protections to make it harder to accidentally install ont-fast5-api on python 2.

**Comment by aman21392** [comment]
Thanks its working.

**Comment by fbrennen** [comment]
Great to hear. =)
