### ISSUE TITLE
no space left on device [errno28]

### ISSUE THREAD

**Issue by lucio-cyber** [nanoporetech/ont_fast5_api#42]
Hi, I tried to convert multi fast5_pass into sigle fast5 with the following command : multi_to_single_fast5 -i fast5_pass -s fast5_single --overwrite
but at the end of this command some reads seem to have not been placed in the 'fast5_single' folder. How can I solve these problem? 
Best Regards

**Comment by fbrennen** [comment]
Hi @lucio-cyber -- are you saying that you did not have enough disk space to write out all the single-read files?

**Comment by lucio-cyber** [comment]
Yes, at the end of the process, the shell says me “no space left on device” with the reads that are missing. 
But it is strange because I am on the server not on my pc, could it be that having created a space, this same space is too small? Or does it concern anything else?

**Comment by fbrennen** [comment]
I would check the space left on your server, and specifically in the output folder (try `df -h fast5_single` to see how much space is available) -- the error you're seeing is not from `ont-fast5-api`, but from your filesystem.

**Comment by lucio-cyber** [comment]
Okay, he says to me:
Filesystem Size Used Avail Use%
Tank             27T  27T       0 100%

**Comment by fbrennen** [comment]
That'll do it -- 100% used means you have no space left on your device. You'll need to free some up.

**Comment by lucio-cyber** [comment]
Sorry if I answer now, I did a couple of tests but when I start the command “multi_to_single_fast5 -fast5_pass -s fast5_single - - recursive -t 80” it always hangs at the same point, why ? 
I made some space always stopping at the same point "\  3184 of 3585 |################     | 88% ETA:  0:44:26". 
What can depend on the size of my fast5_pass file?

**Comment by lucio-cyber** [comment]
Ok I checked, it's definitely a question of space ... I had also clogged the server. Some advice ?

**Comment by fbrennen** [comment]
There's not a whole lot to say here, unfortunately -- fundamentally you need to find more space. You could try and work on a smaller number of files in the meantime.

**Comment by lucio-cyber** [comment]
Ok ok, thanks so much for your support! 
Best regards
