### ISSUE TITLE
mounting error

### ISSUE THREAD

**Issue by Xiaojuan-Liang** [nanoporetech/ont_fast5_api#52]
Hello, I have some questions in this part.
I have installed the ont-fast5-api:

$pip3 install ont-fast5-api
Requirement already satisfied: ont-fast5-api in .../python3.8/site-packages (3.3.0)
Requirement already satisfied: packaging in .../python3.8/site-packages (from ont-fast5-api) (20.8)
Requirement already satisfied: h5py>=2.8 in .../python3.8/site-packages (from ont-fast5-api) (3.1.0)
Requirement already satisfied: progressbar33>=2.3.1 in .../python3.8/site-packages/progressbar33-2.4-py3.8.egg (from ont-fast5-api) (2.4)
Requirement already satisfied: numpy>=1.16 in .../python3.8/site-packages (from ont-fast5-api) (1.19.1)
Requirement already satisfied: pyparsing>=2.0.2 in .../python3.8/site-packages/pyparsing-3.0.0b2-py3.8.egg (from packaging->ont-fast5-api) (3.0.0b2)

But an error occurred at run time:

$multi_to_single_fast5 -h
Traceback (most recent call last):
  File "/home/li/.local/bin/multi_to_single_fast5", line 5, in <module>
    from ont_fast5_api.conversion_tools.multi_to_single_fast5 import main
  File "/home/li/.local/lib/python2.7/site-packages/ont_fast5_api/__init__.py", line 10, in <module>
    from ont_fast5_api.compression_settings import register_plugin
  File "/home/li/.local/lib/python2.7/site-packages/ont_fast5_api/compression_settings.py", line 73
    raise IOError(VBZ_ERROR_MESSAGE.format(register_plugin())) from err
                                                                  ^
SyntaxError: invalid syntax

Could you give me some adivice?

**Comment by fbrennen** [comment]
Hi @Xiaojuan-Liang -- as you can see from your traceback, you have managed to install `ont-fast5-api` as a Python 2 package:

File "/home/li/.local/lib/**python2.7**/site-packages/ont_fast5_api/init.py"

You will need to uninstall it from there first -- I think `pip uninstall --user ont-fast5-api` should work.

**Comment by Xiaojuan-Liang** [comment]
OK, thanks for your reply, let me have a try.
