### ISSUE TITLE
Guppy default modified base calling configuration file doesn't exist

### ISSUE THREAD

**Issue by JayVaz18** [nanoporetech/ont_fast5_api#54]
Hello,

I am trying to run guppy for modified base calling and then use your package to extract the data. However, do you know why the configuration file provided on the [Nanopore Guppy Modified Base Calling Toolkit](https://community.nanoporetech.com/protocols/Guppy-protocol/v/gpb_2003_v1_revv_14dec2018/modified-base-calling) website doesn't exist in the data folder? 

Here is the command I used:

```
guppy_basecaller -i /Users/jakevazquez18/Desktop/guppy -s /Users/jakevazquez18/Desktop/guppy/fast5/mod_out2 --num_caller 10 --records_per_fastq 0 --fast5_out -c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg

```

And got this error:

```
/Desktop/ont-guppy-cpu/data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg does not exist!

```

Can somebody help me understand why? The only configurations file I see in the data folder for DNA base modifications are for 5mC but not 6mA.

**Comment by fbrennen** [comment]
Hi @JayVaz18 -- apologies, the documentation is slightly out of date. We updated the modified base models in [Guppy 4.5.2](https://community.nanoporetech.com/posts/guppy-v4-5-2-release-note), and removed the olds. You should be able to get it to work using this configuration file: `dna_r9.4.1_modbases_5mc_hac.cfg`
