### ISSUE TITLE
multi_to_single_fast5 generated only 4000 single fast5

### ISSUE THREAD

**Issue by Johnsonzcode** [nanoporetech/ont_fast5_api#55]
Hi, Forrest

I want to use multi_to_single_fast5 to get sinlge fast5 files for downstream analysis. Unfortunately I use the following code but got only 4000 single fast5 files.
(nanopolish) [poultrylab1@pbsnode01 run1]$ multi_to_single_fast5 -i run1_pass_fast5 -s run1_pass_fast5_single --recursive -t 100
| 1 of 1|#############################################################################################################################################################################################################|100% Time: 0:00:06
(nanopolish) [poultrylab1@pbsnode01 run1]$ cd run1_pass_fast5_single/0/ && ls |wc -l
4000

Need help! Thanks in advance！

**Comment by fbrennen** [comment]
Hi @Johnsonzcode -- how many fast5 files are in that folder? Can you print some of the output of `ls run1_pass_fast5/0/` here?

**Comment by Johnsonzcode** [comment]
4000

**Comment by Johnsonzcode** [comment]
-rw-rw-r-- 1 poultrylab1 poultrylab1  81K Jun 24 16:22 008d21c2-36d2-4a7c-ac97-a35b8c55cca7.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1 184K Jun 24 16:22 00847582-c127-4736-bd57-3e70714ef741.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1  64K Jun 24 16:22 00846d89-a848-4a55-a530-dfccbba4c941.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1 505K Jun 24 16:22 007a8686-bc2a-46c9-8628-4a7dbb30c2c3.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1  85K Jun 24 16:22 004c541a-81d9-4865-8535-ddd6fb85f051.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1 172K Jun 24 16:22 00498b18-5bcc-4f73-bba0-414a3b67df3e.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1  97K Jun 24 16:22 003dffcc-d0cc-40c8-8a33-b260006d9569.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1  47K Jun 24 16:22 001cede0-f1c2-4fbc-b415-75c5e7ca9e77.fast5
-rw-rw-r-- 1 poultrylab1 poultrylab1 166K Jun 24 16:22 001130e1-836c-44ce-bb6f-c5af6d8659a5.fast5

The last 9 lines.

**Comment by Johnsonzcode** [comment]
My multipe fast5 file size
(nanopolish) [poultrylab1@pbsnode01 run1_pass_fast5]$ ll
total 456G
-rwxrwxr-x 1 poultrylab1 poultrylab1 456G Jun 22 21:33 all_fast5_pass.fast5

**Comment by fbrennen** [comment]
Apologies, I meant how many fast5 files are there in your *input* folder (`run1_pass_fast5`) -- the output you've pasted looks like the output folder to me.

**Comment by Johnsonzcode** [comment]
`run1_pass_fast5` is my multiple fast5 file, only one file.

**Comment by Johnsonzcode** [comment]
I use `h5ls`  to check my fast5 file:
(nanopolish) [poultrylab1@pbsnode01 run1_pass_fast5]$ h5ls all_fast5_pass.fast5 | wc -l
4000

It seems only 4000 fast5 records in it, but I got so many reads from biotech company.

**Comment by fbrennen** [comment]
Ah, ok, so it does look like `multi_to_single` is working correctly. Usually there will be 4000 reads per multi-read file (just like you're seeing), so I would have expected your biotech company to provide you with many more files than just the one. I would check with them and see if there are more files, or if this file has been packed in some odd way that's hiding some of the reads -- a size of 456G suggests there should be quite a lot more reads in there than just 4000.

**Comment by Johnsonzcode** [comment]
Yes, I think this fast5 file should contain much more reads or single fast5 records based on file size, have ever encounter this situation?

**Comment by fbrennen** [comment]
I haven't! We don't normally put more than 4000 reads into a file, so I'm curious how  your biotech company generated this large one. Is there any chance it's a zip file or another archive of some sort?

**Comment by Johnsonzcode** [comment]
I am contacting company right now, maybe anothor software to compress fast5.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nanoporetech/ont_fast5_api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 晚上6:54
***@***.***&gt;;
抄送:&nbsp;"Johnson ***@***.******@***.***&gt;;
主题:&nbsp;Re: [nanoporetech/ont_fast5_api] multi_to_single_fast5 generated only 4000 single fast5 (#55)





 
I haven't! We don't normally put more than 4000 reads into a file, so I'm curious how  your biotech company generated this large one. Is there any chance it's a zip file or another archive of some sort?

**Comment by Johnsonzcode** [comment]
Thanks a lot!

**Comment by ssscj** [comment]
> Thanks a lot!

Hi, I met the same problem. Have you found the solution? Thanks.
