### ISSUE TITLE
ERROR:ont_fast5_api.conversion_tools.multi_to_single_fast5:Unable to open file

### ISSUE THREAD

**Issue by 123chenshixin** [nanoporetech/ont_fast5_api#57]
Hello,
  I'm trying to convert multi_fast5 to single_fast5 by using multi_to_single_fast5.But there is a problem.

> ERROR:ont_fast5_api.conversion_tools.multi_to_single_fast5:Unable to open file (truncated file: eof = 26173440, sblock->base_addr = 0, stored_eof = 158976592)
        Failed to copy files from: ./fast5_pass/PAG40934_pass_barcode07_3f765e83_85.fast5

And it repeats a lot. Then I find that almost half of multi_fast5 files have this problem. Why this happen?
My command:
`multi_to_single_fast5 -i $multiple_fast5_path -s $single_fast5_path -t 60 --recursive`

**Comment by fbrennen** [comment]
Hi @123chenshixin -- that usually means those files are corrupt. Are you able to open them with tools like hdfview or h5dump?
