### ISSUE TITLE
problem with duplicate name

### ISSUE THREAD

**Issue by lfaino** [nanoporetech/ont_fast5_api#6]
Dear Dev,
i have a problem with multi_to_single_fast5.py tool.
currently i`m using the latest version of MinKNOW which gives multifast5 files. I need to demultiplex these files and i would like to use Deepbinner but the tool does not support multifast5. 

i found this work around:

`multi_to_single_fast5 -i fast5_moved/ -s multiple_fast5/ -n 4000`
to split multi fast5 to single fast5 and after

`deepbinner realtime --in_dir multiple_fast5/ --out_dir demultiplexed_fast5s --rapid`
to demultiples the single fast5 files.

however deepbinner says: "could not move 8800 fast5 files because they already exist in demultiplexed_fast5" 

when i go to check the original output of the multi_to_single_fast5, i see that there are files with the same name in different subfolders.
this is strange. 
could you please check
Cheers
Luigi

**Comment by fbrennen** [comment]
Hi @lfaino -- have you tried running multi_to_single_fast5 with just one multi-read fast5 file, to see if it works with deepbinner? You should not be getting duplicate files in different directories unless you start with duplicate reads.
