### ISSUE TITLE
Issues attempting to duplicate reads

### ISSUE THREAD

**Issue by CodingKaiser** [nanoporetech/ont_fast5_api#61]
Hi there. I am currently trying to use the API to take reads within a fast5 file and duplicate each of them 10-fold. For this purpose, I have written a small script which loads in reads from a MultiFast5File, and for the desired number of duplicates, creates a new, random uuid, putting a copy of the read with the new uuid in a new file. Here is the code:

```python

id_tree = dict()
with MultiFast5File(str(output_file), 'w') as output_f5:
    reads_present = set(output_f5.get_read_ids())
   
    for read_id, read in yield_fast5_reads(input_file, recursive=False):
        id_tree[read_id] = []

        dup_read_id = read_id
        for _ in range(dup_num):
            while dup_read_id == read_id or dup_read_id in reads_present:
                dup_read_id = str(uuid4())
            read.read_id = dup_read_id
            output_f5.add_existing_read(read, target_compression=target_compression)
            reads_present.add(dup_read_id)
            id_tree[read_id].append(dup_read_id)
```

Because I want files with batches of 4000, I then run multi_to_single_fast5.py on the resulting files, followed by single_to_multi_fast5.py. However, this last step throws many error messages, all of the form:

```text
ERROR:ont_fast5_api.conversion_tools.single_to_multi_fast5:Unable to create group (name already exists)
	Failed to add single read file: './hp_fast5_split/6/a26bf700-6d3d-4df0-a7ad-39a34f424e58.fast5' to './hp_fast5_batch/batch_3.fast5'
```

As far as I understand it, each time `add_existing_read` is called, a new group name should be created using the new read_id. Based on this error message, this doesn't seem to be happening, however. While I could just adjust my script to do the batching myself, the error message makes me unsure of whether I am correctly making copies of the individual reads. 

Thanks for your help.

**Comment by fbrennen** [comment]
Hi @CodingKaiser -- thanks for getting in touch. Could we have a look at one of the multi-read files your script produced (before you called `multi_to_single` or `single_to_multi` on it)?

**Comment by fbrennen** [comment]
Good to hear! Glad you've got it working.
