### ISSUE TITLE
subset obtained with fast5_subset does not work for guppy

### ISSUE THREAD

**Issue by ndierckx** [nanoporetech/ont_fast5_api#67]
Hi,

I made a subset of only 2 reads, but i get this error when i run guppy on that file: "Segmentation fault (core dumped)"
While on the original file guppy works fine.
Any idea what the problem could be?

**Comment by fbrennen** [comment]
Hi @ndierckx -- apologies for the delay, this one slipped through the net! Are you still having this issue? If so, could you please tell us what command you used to create the subset? Could we have the file that was created as well?

**Comment by ndierckx** [comment]
Hi,

No problem. The problem is fixed by using a sequencing summary file instead of a list of read ids.
It turns out when I used the list of read ids, the fast5 file was not containing the read data
There were no errors so not sure what the problem was but it works great with the sequencing summary file!

**Comment by fbrennen** [comment]
Ok, great -- glad you figured it out! We'll have a look at whether or not we can reproduce your original issue.
