### ISSUE TITLE
demultiplexing generates additional - folder

### ISSUE THREAD

**Issue by Fatihlrcfs** [nanoporetech/ont_fast5_api#68]
Hi Dear,
I am working on one of the barcoded fast5 files demultiplexing and ı am using this  < demux_fast5 --input fast5_skip/ --save_path demultiplexed_reads/ --summary_file sequencing_summary_FAP54362_e8e82a0a.txt > sequencing summary was provided by ONT Minknown. During demultiplexing additional from the barcode folders (-) folder is generated. Also, all demultiplex fast5 is placed into that folder and my barcode folder is empty. I already base called this data and ı did not face the same problem while ı was working and generating fastq files. now ı am working on another analysis program and ı needs single fast5 so ı am doing demultiplexing. how can ı corretly classify my demultiplex fast5 files from the skipped files. thanks

**Comment by fbrennen** [comment]
Hi @Fatihlrcfs -- `demux_fast5` sorts reads that have already been demultiplexed and had a barcode classification assigned to them. The `fast5_skip` folder contains reads that MinKNOW "skipped" and did not basecall or demultiplex -- this is why they all get put into that `-` folder (meaning there is no demultiplexing result for them). If you want to demultiplex the reads from the skip folder you will need to use guppy.

**Comment by Fatihlrcfs** [comment]
Hi @fbrennen sorry for my disturbance but ı am quite new to this area and ı don't know how to deal with this problem. ı need single fast5 files for Deeepsignal and Tombo analysis. I read the guppy and did not find how to generate single fast5 files from the fast_skip using guppy. if it is possible could you explain me more basic ? manny thanks. Sincerely
