### ISSUE TITLE
multi_to_single_fast5 problem

### ISSUE THREAD

**Issue by FerchoHQ** [nanoporetech/ont_fast5_api#69]
Hello, I have an issue, when I used multi_to_single_fast5 in order to get a single fast5 file, I find a folder with too many fast5s for each fast5 file that I have; in other words, the program multiplies the number of files by ten times or more. My script:

multi_to_single_fast5 -i /work/yaolab/fernandohq/2021-Dec-assembly_dataset/SRR12801740-ecoli-ontlig \
    -s /work/yaolab/fernandohq/2021-Dec-assembly_dataset/SRR12801740-ecoli-ontlig --recursive -t 32

Thanks for your attention.

**Comment by fbrennen** [comment]
Hi @FerchoHQ -- `multi_to_single_fast5` creates *single-read fast5 files* (an old format that is now deprecated, but that is still used by some legacy software). It sounds like it's performing exactly as expected. If you want to repack your fast5 files then you should use `fast5_subset`, though you will need to start by producing a list of all the read_ids present in your files for the `--read_id_list` argument.
