### ISSUE TITLE
error when converting single read to multi read

### ISSUE THREAD

**Issue by Vsd1106** [nanoporetech/ont_fast5_api#77]
I have been converting single read fast5 files to multi read fast5 and been faced with some errors when trying to convert them to pod5. I assumed the issue is related to the conversion process:Unable to open the group "Raw": (Symbol table) Object not found

**Comment by hb-nanopore** [comment]
Looks like this is being addressed with you by Rich in https://github.com/nanoporetech/pod5-file-format/issues/52 so I'll close it here, but re-open if you still have problems.

Thanks

Hayleigh
